### PR TITLE
Enable logging in public mode and load messages on connect

### PR DESCRIPTION
**Pull request by jdve**
Always log messages, even in public mode, as in #295.  Messages will only be logged as long as at least one public client is connected to a channel.  When all clients disconnect, messages aren't logged anymore.

Also, load messages from the log file when joining a channel.

### CODE REVIEW

**Comment by furier** [comment]
:+1:

**Comment by aynik** [comment]
I think we may be interested in joining efforts here, I've submitted a pull request (#391) which adds log file parsing too. Are you parsing events too or just messages?

**Comment by jdve** [comment]
Sure!  I'm only parsing messages right now, but I'm sure my changes could fit on top of yours.

**Comment by astorije** [comment]
Hi there,

Quick question: what are the benefits of logging public instances?
In particular, assuming we display scrollback based on logs (/!\ not yet implemented), if someone logs with username `foobar`, logs out, and someone else logs with username `foobar`, does that mean the second user will be able to look at the first user's logs?!

**Comment by furier** [comment]
@astorije good question, I would guess this would only be for public channels "you" enter. Tho logging in public mode without any login makes no sence to me...

**Comment by astorije** [comment]
I'm really confused by this PR. Why would you log public instances?
The only reason I can find is if Shout crashes, and I don't think this PR addresses such use case.
Also, it seems like this PR is adding their own favored in-memory cache while there is already such mechanism for private instances. Why using a new dependency?

I don't think I'm going to give a thorough review to this until @jdve comes back here (or on the IRC channel) because these are important questions to answer before considering a merge. I also invite @JocelynDelalande to come give his input here if he finds the time.

**Comment by JocelynDelalande** [comment]
@astorije benefit is : when you join a channel, you get the recent history of the channel (so it gives you context), I experimented it with [yunohost jabber chan](http://yunohost.org), it's quite handy.

On the other hand, I think enabling this by default for all chans is quite dangerous from a privacy standpoint.

In fact, with your patch, stop me if I'm wrong @jdve (haven't tested, just read), but if I log to the same shout server as you, I will even recover the history from your private chats (queries).

The privacy issue is huge with queries, but also present with public chans where a user may not thinks he is logging publicly the chan to the world.

IMHO such a feature is acceptable only if : 

- it's disabled for queries
- it's enabled by shout admin on a per-chan basis

**Comment by astorije** [comment]
> it's enabled by shout admin on a per-chan basis

Even that is a big problem privacy-wise IMO. When I was at W3C for example (on W3C IRC server), we were often "gathering" in small rooms and expecting not to be logged.

Usually, logging public channel is taken care of by owners of the channel, through a bot, and they often advertise in the topic that the channel is being logged.

I still think that logging on the shout server for public instances could be very harmful. Essentially, I could imagine myself asking people if they are using Shout operated by someone else than themselves before speaking freely.

**Comment by JocelynDelalande** [comment]
> it's enabled by shout admin on a per-chan basis
> 
> Even that is a big problem privacy-wise IMO. When I was at W3C for example (on W3C IRC server), we were often "gathering" in small rooms and expecting not to be logged.

Yep, but using something like shout, you are already in a situation where you trust shout admin server not to deliberately spy on you. The threat model don't really change.

> Usually, logging public channel is taken care of by owners of the channel, through a bot, and they often advertise in the topic that the channel is being logged.

Well… I know several channels which are being logged by individuals buddies, without specific rights, and sometime published , because they consider it a public place.

Maybe display some icon when it's a logged channel ?

**Comment by astorije** [comment]
> Yep, but using something like shout, you are already in a situation where you trust shout admin server not to deliberately spy on you. The threat model don't really change.

Yet again I am all opposed to designing a system that expects everyone to be super nice. We have seen too much in the past that some people are actually using these assumptions to do mass surveillance. There shouldn't be a reason to avoid designing secure systems, even in a situation where you trust your sysadmin.

> Well… I know several channels which are being logged by individuals buddies, without specific rights, and sometime published , because they consider it a public place.

Correct, but again that's very different. If you discuss on a public channel with dozens of users you don't know, you pay attention to what you say. If you are creating a "private" (as in not sharing the channel name with others) channel between you and your parents (or a couple of colleagues or whatever) about sensitive details and you know these ones are trustworthy enough when you wonder if they are logging this channel, do you really expect the admin to log what you say? I clearly wouldn't.

> Maybe display some icon when it's a logged channel ?

That might be a decent minimal requirement for this, but I am still not entirely sold on the matter...

**Comment by JocelynDelalande** [comment]
> it's enabled by shout admin on a per-chan basis

@astorije I'm 
not sure you replied about the per-chan thing, if the adminsys deliberately logs a channel, that's a volunteer and targeted "spying", it's easy to do it by other means (eg HTTP logging), and preventing that is out of our scope IMHO. It's not "mass" and by default logging, which is, I agree with you, to avoid.

**Comment by astorije** [comment]
> @astorije I'm not sure you replied about the per-chan thing, if the adminsys deliberately logs a channel, that's a volunteer and targeted "spying", it's easy to do it by other means (eg HTTP logging), and preventing that is out of our scope IMHO. It's not "mass" and by default logging, which is, I agree with you, to avoid.

I [did answer](https://github.com/erming/shout/pull/392#issuecomment-143890993).
Anyway, I disagree with that comment, but I am done explaining why. Feel free to self-assign that PR if you want to follow up with it.

**Comment by Xe** [comment]
Who's to say the irc server administrator is not also spying on you?

You gotta trust someone somewhere eventually. That's just how stuff works.

**Comment by floogulinc** [comment]
I honestly don't see much of a point in this feature and I think it has too many possible problems. Most people would expect the current behavior when in public mode, to basically act as a normal web IRC client.

**Comment by JocelynDelalande** [comment]
Ok, trying to sum up things before it turns into troll (feel free to amend if it seems not to reflect the debate).

## Proposed features

(as submitted by @jdve)

- log all messages in public modes (query & public chans)
- load the logs on start

## Pros

- gives context when you join a chan
- simple and natular access to chan backlog

## Cons (without modifications)

- I can pretend to be any user and gets its query (or small "private" chans) log
- Can be used as per-default "spying" tool by adminsys and anyway

## Proposed modifications

- do not log anything by default
- adminsys can enable per-chan logging
- display an icon to warn user on a logged chan (it only warns local shout users, not other users)

## Cons (with proposed modifications)

- could still be used by shout admins to target some chan logging
- may be an unexpected behaviour

**Comment by JocelynDelalande** [comment]
## Proposal
As :
- there is a disensus on that PR even with modifications
- @jdve seems no longer active on this

Let's reject and close this PR for now.

If one day we want change our mind, we will have the debate summary I did just before as a starting point.

What do you think ?

**Pull request closed without merging**
