### PR TITLE
Change user buttons to as. Allows highlighting on firefox.

### PR DESCRIPTION
**Pull request by YaManicKill**
On firefox, we can't copy the usernames when it is a button. Change to span.

### CODE REVIEW

**Comment by astorije** [comment]
Any side effect on this? In particular, empty `href`s tend to not be consistently working. I'll look into it, and if so maybe `href="#"` would do the trick.
Nice catch though! :-)

**Comment by astorije** [comment]
Dumb dumb dumb dumb me! I clicked "Merge" instead of "Comment", and force of daily habit I confirmed the merge right before realizing I made a mistake! Duh!

Sorry but do you mind reopening a PR please? :-/

**Comment by YaManicKill** [comment]
Hmmm, github says that there are no differences now between my branch and master, so I can't open a new PR.

**Comment by YaManicKill** [comment]
Also, woops I did mean to put href="#", not sure why I didn't. I'll update that.

**Pull request merged**
