### PR TITLE
Fixing initial copyright year

### PR DESCRIPTION
**Pull request by pra85**
According to http://www.copyright.gov/circs/circ01.pdf , document should list its first year of publication in its copyright

### CODE REVIEW

**Comment by astorije** [comment]
:+1: 

@erming, can you confirm?

**Comment by erming** [comment]
https://github.com/erming/shout/commit/196f9aa551434fd5ce38247788e45cd8ab2172ba — Mars 4, 2015

Doesn't feel like it was that long ago!

+1 for merge

**Comment by astorije** [comment]
@erming, you meant 4 March **2014** :-)

Merging!

**Comment by astorije** [comment]
Thanks @pra85!

**Pull request merged**
