### PR TITLE
Add a copy of the MIT license

### PR DESCRIPTION
**Pull request by Calinou**
It is good practice to add a copy of the license to the repository.

### CODE REVIEW

**Comment by astorije** [comment]
Hi @Calinou, thanks! I already added one in a PR of mine: #465. Feel free to :+1: there if you think we should have badges as well :D

**Comment by JocelynDelalande** [comment]
@astorije as I think there will be consensus on that PR before #465 let's merge this one and rework yours to remove the license thing, what do you think ?

If you agree on that, I give my :+1: for that trivial (but good to see) one.

**Comment by astorije** [comment]
Agreed, @JocelynDelalande. I'll merge this and rebase my PR accordingly, reeeeally hoping @erming changes his mind (and in the meantime, I encourage folks to either :+1: or :-1: on #465).

I'd prefer a non-Markdown file for the license, but no strong opinion. I'm :+1: on this and will merge, but I'd be curious if you usually prefer a raw text file or not, @JocelynDelalande.

**Comment by JocelynDelalande** [comment]
> I'd be curious if you usually prefer a raw text file or not, @JocelynDelalande.

I prefer sticking to the verbatim text, but that's not a strong opinion though.

**Comment by floogulinc** [comment]
The default when you create a LICENSE file on GitHub is raw text. You can see this if you go and click the add file button on a repo and type `LICENSE` in the title, it will suggest licenses to the right, which are raw text.

**Comment by astorije** [comment]
Fair enough, I opened a PR to go raw then :-)

**Pull request merged**
