### PR TITLE
Added zenburn theme

### PR DESCRIPTION
**Pull request by japesinator**
Added a zenburn theme based on the existing morning theme

### CODE REVIEW

**Comment by Sunako** [comment]
Do want

**Comment by erming** [comment]
Hey man, I just had a look at the theme.

It looks unfinished:

zenburn

Sorry, but I didn't like it in the current state. I really do appreciate the effort though!

If you could try to improve it and be more thorough, I might have a look at it again.

_I'll keep this PR open in case you want to continue working on it._

**Comment by japesinator** [comment]
Yeah, that's totally fair.  To be honest, I only really looked at the chat window when I was testing it.  I'll make the settings/connect/etc. screens look better.

**Comment by dideler** [comment]
@japesinator please do post screenshots when you've made visual changes, as it gives others a quick overview of the changes without having to pull the code. Thanks for working on a new theme!

**Comment by japesinator** [comment]
Alright, I cleaned things up a little.  Let me know what you think now

**Comment by YeahToast** [comment]
Wow!! Sexy!

**Comment by erming** [comment]
Thanks!

**Pull request merged**
