### PR TITLE
Improved TAB completion on client

### PR DESCRIPTION
**Pull request by doppioandante**
Fixes(?) #297 
Requires fuse.js
I'm not a javascript programmer, please review with suspicion.
EDIT: I should probably make travis green first. Also, I need to add a line or two to the changelog before you merge.

### CODE REVIEW

**Comment by doppioandante** [comment]
I've tried to make the completion smarter by looking at a bunch of the last messages and extracting they nicks. Those will be suggested first. #434 
I had to modify jquery/tabcomplete.js, as I explain in the commit message.

I'll wait for suggestion before doing any further work.

**Comment by doppioandante** [comment]
I've been using this feature since and it works.
I've been wondering whether the fuzzy search is overblown though, maybe just skipping the first weird characters of the nicknames is good enough as a heuristic.

**Comment by jcrben** [comment]
This should be submitted to https://github.com/erming/tabcomplete and shout can pull in the update from there.

**Comment by MaxLeiter** [comment]
as a note, tab completion is being over-hauled in thelounge/lounge#787

**Pull request closed without merging**
