### PR TITLE
Use forever to restart shout when it dies.

### PR DESCRIPTION
**Pull request by YaManicKill**
Just a small PR to run forever within shout itself. I've added this onto my fork, and thought I would share it to see if the team wanted it in Shout. 

I could add the restart numbers to the config, if people think that would be best?

### CODE REVIEW

**Comment by dgw** [comment]
Personally, I think this is best left to systemd/upstart/whatever service manager.

**Comment by astorije** [comment]
The way I understand it, this would break shout for all those who use any service manager (as @dgw said, upstart, systemd, I personally use supervisor) to deal with this.

Additionally, I am :-1: on these additions as it forces us to maintain lots of things outside the project itself.

@YaManicKill, what about an external repo you control and manage for those who want to use forever? Then we can list these sort of projects that rotate around shout. When we move Shout to its own organization, we'll be able to integrate some of the best maintained projects back to the organization and made them "official", under conditions :-)

**Comment by YaManicKill** [comment]
So essentially a wrapper around shout. Yeah, that would work fine, as it gives the exact same functionality, but is essentially an opt-in for people. Closing this PR and I'll get that done sometime.

**Comment by astorije** [comment]
@YaManicKill, feel free to add documentation about this in the wiki when you are done :-)

**Comment by astorije** [comment]
@YaManicKill, any chance you could add a paragraph here: https://github.com/erming/shout/wiki/Alternative-Install-methods ?

**Pull request closed without merging**
