### PR TITLE
add development setup instructions, thanks @hennevogel, fix #355

### LINKED ISSUE #355: Instructions on how to run from source
Hey @erming – great work on this IRC app!

I want to run it from source to contribute the odd design-enhancement. We also want to deploy it for @opensourcedesign. The instructions are only for installation via npm and my node knowledge is a bit spotty.

Can you enlighten me on how to run it from source? Would be cool if that dev/contributing setup is also in the readme. :)

### PR DESCRIPTION
**Pull request by jancborchardt**
Please review @erming, this adds instructions on how to run from source as asked about in #355. (Thanks to @hennevogel)

### CODE REVIEW

**Comment by wizardfrag** [comment]
You should just use `npm install`, as `sudo npm install` will create files in the local directory as root.

`sudo npm install` should only be used for global Node modules

**Comment by jancborchardt** [comment]
@wizardfrag right, updated!

**Comment by AmShaegar13** [comment]
I would add that you need to run `grunt` if you modified anything in `/client/js/libs` or `/client/views`

**Comment by jancborchardt** [comment]
@erming thanks!

**Comment by erming** [comment]
No, thank you @jancborchardt ;)
And sorry about the loooong response time from me.

I made some minor changes to the text though – mostly because of my own personal preference. Running Shout via `node index.js` works just as well.

**Pull request merged**
