### PR TITLE
Nicer scrollbar (webkit only)

### PR DESCRIPTION
**Pull request by xPaw**
Looks like this:
chrome_2016-01-18_19-49-33
chrome_2016-01-18_19-50-05
chrome_2016-01-18_19-51-01

### CODE REVIEW

**Comment by astorije** [comment]
:+1:

**Comment by floogulinc** [comment]
my scrollbar already looks like that and hides (because I'm on Mac). Does this work fine on mobile?

**Comment by xPaw** [comment]
Well it looks like that on a mac, because it sort of mimicks it. And yes, it looks absolutely fine on mobile (chrome, android).

**Comment by floogulinc** [comment]
there is already a scrollbar like that on the channel list, is that not using the webkit thing?

**Pull request merged**
