### PR TITLE
Expand links with Embed.ly

### PR DESCRIPTION
**Pull request by gaving**
Added support for expanding links/images with [Embed.ly cards](http://embed.ly/cards).

#35 relates, effectively reverts #228 and removes the `prefetch`, `links` and `thumbnails` options (plus a bunch of dependencies).

In action:-

screen

Settings:-

settings

### CODE REVIEW

**Comment by spencerthayer** [comment]
@erming have you found the time to merge this.

**Comment by JocelynDelalande** [comment]
:-1: huge privacy concerns about that, it logs every url to an external, centralized and proprietary service.

**Comment by floogulinc** [comment]
[embed.js](https://github.com/ritz078/embed.js) might be a great alternative to this.

**Comment by YaManicKill** [comment]
I'm assuming this isn't going in because of being a 3rd party service. It might worth adding as a plugin if that ever gets done, but this could probably be closed for now?

**Comment by astorije** [comment]
Yes, make this a third-party package is the right route, as people need to be aware of the privacy concerns before committing to using that.

**Pull request closed without merging**
