### PR TITLE
Fixing issues #54: Add shout to docker

### PR DESCRIPTION
**Pull request by PierreZ**
Wrote thank's to @furier a valid Dockerfile valid for private and public shout server!

README.md in data/{logs,users} are just here to create the hierarchy.

All the commands are in the main README.md

### CODE REVIEW

**Comment by ryanseys** [comment]
The current Docker instructions [here](http://shout-irc.com/docs/deployment/docker.html) reference a Dockerfile that does not exist. This PR should fix that.

**Comment by czak** [comment]
How about a `Dockerfile` which actually uses the repo code?

```
FROM node:latest

COPY . /src 
RUN npm install -g /src
 
EXPOSE 9000
 
CMD ["shout"]
```

Differences from the Dockerfile proposed in this PR:

* `USER root` is not needed, `root` is [default in the container](http://docs.docker.com/reference/run/#user)
* copy and install from the source in current folder (i.e. the repository)
* `CMD` instead of `ENTRYPOINT` so you can override the command in `docker run`

That's how I set it up in [my fork](https://github.com/czak/shout). Then you can set up an [automated build](docs.docker.com/docker-hub/builds/) on Docker Hub so everyone will be able to:

```
$ docker run -p 9000:9000 erming/shout
```

...without building the image themselves. And it will stay up to date on Docker Hub.

> I don't think you need that data folder. 
> You can just mount /root/.shout from container to any host directory and the application will create the needed structure.

:+1: to this. With docker everyone can place the configs wherever they like.

**Comment by hashworks** [comment]
Just a tip: You can refere to issues by adding stuff like "resolves #54" to your pull request description. This way the issue will also get closed automatically when this get's merged. Magic!

**Comment by PierreZ** [comment]
@czak is right. I'm closing my PR

**Pull request closed without merging**
