### PR TITLE
Initial work on context menus

### PR DESCRIPTION
**Pull request by xPaw**
chrome_2016-01-25_15-47-56

### CODE REVIEW

**Comment by MaxLeiter** [comment]
Just adding my two cents: I think on mobile the context menu should exist elsewhere as a button, similar to the 'leave' one. Perhaps we can replace the current leave channel ('x') button with a dropdown arrow?

**Comment by xPaw** [comment]
I would rather try to make long press work instead of adding arrows.

**Comment by YaManicKill** [comment]
I agree with @xPaw 

For a button to work, we would need to increase the size of the sidebar, as trying to hit a button on that small name is near impossible currently (it's hard enough to hit the expando for link expander just now as it is).

**Comment by MaxLeiter** [comment]
If long press opens a context menu then how would mobile users rearrange channels and servers?

**Comment by xPaw** [comment]
At least in Chrome on Android long press simply selects the text, you can't rearrange servers.

**Comment by xPaw** [comment]
Figured out how to make the context menu work on mobiles, by adding `user-select: none;` on the sidebar.

photo_2016-01-30_23-13-13

**Comment by YaManicKill** [comment]
I really like this so far, looks really nice and it brings forward many features to the user, especailyl on mobile.

I think having a longpress on mobile, and right-click on desktop works really nicely as these are things people expect to do something like that.

**Comment by MaxLeiter** [comment]
I agree that longpress make sense on mobile, but I think there should be a way to reorganize channels and servers. That could be built into the context menu (ie “unlock” or “move down”) but that seems like an awkward UX choice

**Comment by YaManicKill** [comment]
We could have a "grabber" (I forget what the proper word for them is) on touch-screen devices that you can use for reordering.

**Comment by xPaw** [comment]
The question is why current grabbing stuff does't work on mobile. That should be triggered long before the contextmenu event.

**Comment by xPaw** [comment]
Closing this in favor of https://github.com/thelounge/lounge/pull/9

**Pull request closed without merging**
