### PR TITLE
Fix #466: Have Travis CI create config folder

### LINKED ISSUE #466: Fix failing build
Badges added in https://github.com/erming/shout/pull/465 emphasize that the Travis CI build is currently failing. This is a friendly reminder to fix that.

### PR DESCRIPTION
**Pull request by astorije**
Thanks @floogulinc for pointing me towards the solution :-)

### CODE REVIEW

**Comment by astorije** [comment]
@erming, @JocelynDelalande, may I have your :+1: on this?

**Comment by erming** [comment]
+1, looks like a simple fix

**Comment by williamboman** [comment]
LGTM

**Comment by JocelynDelalande** [comment]
:+1:

**Pull request merged**
