### PR TITLE
add capability to run at non-root path

### LINKED ISSUE #333: Allow installation at non-root URL
Sometimes I have no control on the domain name I can use and would like to install different services such as shout-irc, so I need to install it in e.g. `example.org/irc`.

A solution would be to add some `base_url` option in main config.

### PR DESCRIPTION
**Pull request by LouisKottmann**
Hello,

With this PR, setting the new config setting `rootpath` to `/chat` will serve shout at `http://0.0.0.0:9000/chat` (if all other defaults are left untouched).

I tested it with a fresh install and it works just like before, and by setting the new variable and it works as well. 
By "works", I mean the main page shows up without issues, and chatting/reading remain as functional.

this fixes #333 #243 

Have a nice evening!

Louis "Baboon" Kottmann

### CODE REVIEW

**Comment by LouisKottmann** [comment]
This needs more work, do not merge for now

**Comment by astorije** [comment]
Hi @LouisKottmann, I reckon this is old, but did you get your way around this?

I reckon this would also be useful to https://github.com/Kloadut/shout_ynh. Maybe @JocelynDelalande can give some context as I know he has been around making sure projects work in path-based URLs.
In particular, is it worthwhile compared to handling the subfolder in nginx instead?

**Comment by LouisKottmann** [comment]
@astorije sorry I'm not using it anymore and I'm way out of touch on this PR since I had no feedback at the time. Good luck to you.

**Comment by astorije** [comment]
Sorry to hear that @LouisKottmann :-(
Feel free to come back if you ever need to, and be sure that we'll do our best to give you quick feedback this time!

**Pull request closed without merging**
