### PR TITLE
Allow shout-irc to be hosted behind a /path/ in a proxy

### PR DESCRIPTION
**Pull request by gdamjan**
Typical nginx config is:

```
  location /irc/ {
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_pass http://localhost:9000/;
  }
```

ps. the trailing `/`s are important both in `location` and `proxy_pass`.

the changes make all the urls that shout-irc uses to be relative.

### CODE REVIEW

**Comment by YaManicKill** [comment]
Looks good. Nice and simple, I'll have a play around to double check you didn't miss anything, but it does seem to be all that's needed. I was about to ask about the JS files, but it seems they are already relative.

**Comment by gdamjan** [comment]
fixes #333 #346

**Comment by MaxLeiter** [comment]
@gdamjan might want to squish the commits, otherwise looks good :) :+1:

**Comment by gdamjan** [comment]
i'll do that as soon I get home tonight

**Comment by astorije** [comment]
FYI, this has been implemented in The Lounge: https://github.com/thelounge/lounge/pull/3 and https://github.com/thelounge/lounge/pull/20.

I'm wondering if we should fix these (PRs that have made it to The Lounge).

**Comment by gdamjan** [comment]
updated

**Comment by gdamjan** [comment]
not going anywhere

**Comment by MaxLeiter** [comment]
@gdamjan in case you didn't see from @astorije's comment, Shout is now inactive, and it has been continued as TheLounge over at https://github.com/thelounge/lounge

**Comment by gdamjan** [comment]
yeah I know, the same patch was accepted in thelounge.
it was jut annoying me in the github pr page

**Pull request closed without merging**
