### PR TITLE
Fix the link plugin test

### PR DESCRIPTION
**Pull request by astorije**
> Travis should work now

Taken from https://github.com/Shuo-IRC/Shuo/pull/31.

### CODE REVIEW

**Comment by astorije** [comment]
Meh, it failed :-(
Do you remember how you fixed that, @Xe or @floogulinc?

**Comment by astorije** [comment]
Closing as this will get superseded by @williamboman in #493, good job to him!

**Comment by floogulinc** [comment]
BTW, i noticed this:
>This job ran on our legacy infrastructure. Please read [our docs on how to upgrade](http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade)
This is probably a cause of our Travis build problems and I bet this PR would work if it was upgraded.

**Comment by astorije** [comment]
@floogulinc, I don't think this is the cause, but it doesn't hurt to use Travis CI's modern infrastructure.

**Pull request closed without merging**
