### PR TITLE
Fix: colored nicknames for new info messages design

### PR DESCRIPTION
**Pull request by bews**
Now they're colored too (if colored nicknames option is enabled).

### CODE REVIEW

**Comment by astorije** [comment]
@bews, do you mind re-opening this on [The Lounge](https://github.com/thelounge/lounge) as well? We are missing this over there and that would be a great addition!

I believe this is the case, but just double-checking this:
Are the colors in the action strings (joins, quits, ...) the same than the ones for message authorship?
That is, if I join and then post a message, will the color be the same?

Also, careful, you have an unintended commit here :-)

**Comment by bews** [comment]
> Also, careful, you have an unintended commit here :-)

Already noticed :)

**Comment by astorije** [comment]
> Already noticed :)

Now you have 2 :-)

```sh
git rebase -i master
# Remove the last 2 commits and save
git push --force
```

**Comment by dgw** [comment]
Ah, the perils of making PRs from the master branch.

**Comment by bews** [comment]
Recreated from branch - #664

**Pull request closed without merging**
